language: node_js
node_js:
  - "10"
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/savjeecoin-frontend
  on:
    branch: master